import os
import os.path
import dnacauldron
import traceback
import re
import threading
from contextlib import contextmanager


_BOLD_MATHTEXT_LABEL = re.compile(r"\$\\bf\{(.*?)\}\$", re.DOTALL)
_REPORT_MATHTEXT_LOCK = threading.RLock()
_MATHTEXT_SPECIAL_CHARACTERS = {
    "#": r"\#",
    "$": r"\$",
    "%": r"\%",
    "&": r"\&",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "\\": r"\backslash{}",
}


def _escape_mathtext_label(label):
    """Escape user-controlled text placed inside a Matplotlib math label."""
    return "".join(
        _MATHTEXT_SPECIAL_CHARACTERS.get(character, character)
        for character in label
    )


def _escape_bold_mathtext_labels(text):
    """Escape labels generated by dna_features_viewer as ``$\\bf{...}$``."""
    if not isinstance(text, str):
        return text
    return _BOLD_MATHTEXT_LABEL.sub(
        lambda match: r"$\bf{" + _escape_mathtext_label(match.group(1)) + "}$",
        text,
    )


@contextmanager
def _safe_report_mathtext():
    """Temporarily protect report labels without changing biological IDs."""
    from matplotlib.mathtext import MathTextParser

    with _REPORT_MATHTEXT_LOCK:
        original_parse = MathTextParser.parse

        def parse_with_escaped_labels(parser, text, *args, **kwargs):
            return original_parse(
                parser, _escape_bold_mathtext_labels(text), *args, **kwargs
            )

        MathTextParser.parse = parse_with_escaped_labels
        try:
            yield
        finally:
            MathTextParser.parse = original_parse



class SupportGG:
    def __init__(self,PartAddress_list, PartName_list):
        self.PartAddress_List = PartAddress_list
        self.PartName_List = PartName_list
        self.repository = dnacauldron.SequenceRepository()
        print(self.PartName_List)

    def assemblyPart(self,name,enzyme = "auto"):
        if not self.PartAddress_List or not self.PartName_List:
            raise ValueError('组装输入为空，请先添加骨架、part 或质粒')
        if len(self.PartAddress_List) != len(self.PartName_List):
            raise ValueError('组装输入文件与元件名称数量不一致')
        if not enzyme:
            raise ValueError('未确定组装酶，请检查骨架的酶切位点')
        temp = len(self.repository.get_all_part_names())
        if(len(self.repository.get_all_part_names())!=0):
            self.repository = dnacauldron.SequenceRepository()
        print(f"part_file_address:{self.PartAddress_List}")
        print(f"part_name:{self.PartName_List}")
        try:
            from pathlib import Path
            from LabDatabase.feature_records import read_genbank
            records = []
            for path in self.PartAddress_List:
                record = read_genbank(path)
                record.id = Path(path).stem
                record.annotations.setdefault('topology', 'circular')
                records.append(record)
            self.repository.add_records(records)
            self.input_records = records
            assembly = dnacauldron.Type2sRestrictionAssembly(parts=self.PartName_List, name = name, enzyme = enzyme)
            # assembly = dnacauldron.Type2sRestrictionAssembly(parts=self.PartName_List,expect_no_unused_parts=False)
            self.simulation = assembly.simulate(sequence_repository=self.repository)
        except Exception as e:
            traceback.print_exc()
            raise
        # assert len(self.simulation.construct_records) == 1
        # assert len(self.simulation.construct_records[0]) == 8016


    def show(self, output_dir="output"):
        from LabDatabase.feature_records import normalized_record, restore_assembly_part_styles
        if not self.simulation.construct_records:
            raise ValueError('Assembly produced no construct: ' + str(self.simulation.errors))
        self.simulation.construct_records[:] = [normalized_record(
            restore_assembly_part_styles(r, getattr(self, 'input_records', [])))
            for r in self.simulation.construct_records]
        print("Show!!!")
        os.makedirs(output_dir, exist_ok=True)
        report_writer = dnacauldron.AssemblyReportWriter(include_mix_graphs=True, include_assembly_plots=True)
        with _safe_report_mathtext():
            self.simulation.write_report(output_dir, report_writer=report_writer)
        from pathlib import Path
        from LabDatabase.feature_records import write_record
        for record in self.simulation.construct_records:
            path = Path(output_dir) / (record.id + '.gb')
            if not path.exists():
                candidates = list(Path(output_dir).rglob(record.id + '.gb'))
                if len(candidates) != 1:
                    raise ValueError('Cannot identify the generated construct file: ' + record.id)
                path = candidates[0]
            write_record(path, record)



    def AddPart(self, records):
        self.repository.add_records(records)

if __name__ == '__main__':
    AddressList = [r'WebDataWorld/output/50f10337-269d-4961-841b-fbc7127dcfc1/ZZ085/provided_parts_records/backbone-769-ZZ031-.gb',r'WebDataWorld/output/50f10337-269d-4961-841b-fbc7127dcfc1/ZZ085/provided_parts_records/plasmid-8244-ZZ014-phiBT1 Integrase.gb']
    FileName = ['backbone-769-ZZ031-', 'plasmid-8244-ZZ014-phiBT1 Integrase']
    test = SupportGG(AddressList,FileName)
    test.assemblyPart("webtest","BsaI")
    test.show()
