"""One conversion boundary: database coordinates are 1-based, inclusive.

Biopython locations remain zero-based, half-open. Normalization never changes
the sequence or rotates its origin. Location segment order is significant.
"""
from collections import OrderedDict
from copy import deepcopy
import hashlib
import io
import json
import os
from pathlib import Path
import tempfile
import uuid

from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqFeature import SeqFeature, SimpleLocation, CompoundLocation
from Bio.SeqRecord import SeqRecord


def _values(value):
    if isinstance(value, (list, tuple)):
        return [str(x) for x in value]
    return [] if value is None else [str(value)]


def first(qualifiers, key, default=''):
    values = _values(qualifiers.get(key))
    return values[0] if values else default


FEATURE_COLORS = {
    'promoter': '#FFCC00', 'p+r': '#FFCC00', 'cds': '#83FF83',
    'terminator': '#74DAFF', 'rbs': '#FFE1C4', 'ori': '#999999',
    'rep_origin': '#999999', 'scar': '#ff0000', 'restriction_site': '#4f46fe',
    'binding': '#cccccc', 'spacer': '#ABABC6', 'homo': '#99CCFF',
    'attp': '#CBE7FF', 'iceyydm': '#cccccc', 'bsubamy': '#cccccc',
    'sgrna': '#FF9CCD', 'misc_feature': '#CCCCCC', 'plasmid': '#CCCCCC',
}


def apply_feature_color(feature):
    """Fill missing viewer qualifiers, preserving explicit source colors."""
    q = feature.qualifiers
    color = (first(q, 'color') or first(q, 'ApEinfo_fwdcolor') or
             first(q, 'ApEinfo_revcolor') or FEATURE_COLORS.get(feature.type.lower()))
    if color:
        for key in ('color', 'ApEinfo_fwdcolor', 'ApEinfo_revcolor'):
            if not first(q, key):
                q[key] = [color]


def restore_assembly_part_styles(record, inputs):
    """Resolve engine-generated annotations by source ID, never filename tokens."""
    sources = {}
    backbone_ids = {source.id for source in inputs
                    if source.annotations.get('assembly_source_type') == 'backbone'
                    or 'polaris_source_type=backbone' in source.annotations.get('comment', '')}
    for source in inputs:
        containers = [f for f in source.features
                      if first(f.qualifiers, 'source_container') == 'true']
        if containers:
            sources[source.id] = containers[-1]
    removed = set()
    def location_key(feature):
        if feature.location is None:
            return None
        return tuple((int(p.start), int(p.end), p.strand) for p in feature.location.parts)

    for feature in record.features:
        if first(feature.qualifiers, 'indicates_part').lower() != 'true':
            continue
        if first(feature.qualifiers, 'source') in backbone_ids:
            removed.add(id(feature))
            continue
        source = sources.get(first(feature.qualifiers, 'source'))
        if source is None:
            continue
        # Merge only a generated whole-part annotation with its matching
        # inherited container at this insertion location. Real internal
        # features, including coextensive ones, are never deduplicated here.
        matches = [candidate for candidate in record.features
                   if candidate is not feature
                   and first(candidate.qualifiers, 'source_container') == 'true'
                   and first(candidate.qualifiers, 'feature_group') == first(source.qualifiers, 'feature_group')
                   and first(candidate.qualifiers, 'source_type') == first(source.qualifiers, 'source_type')
                   and first(candidate.qualifiers, 'source_id') == first(source.qualifiers, 'source_id')
                   and location_key(candidate) == location_key(feature)]
        if len(matches) == 1:
            container = matches[0]
            for key, value in feature.qualifiers.items():
                if key not in ('feature_group', 'color', 'ApEinfo_fwdcolor', 'ApEinfo_revcolor'):
                    container.qualifiers.setdefault(key, _values(value))
            apply_feature_color(container)
            removed.add(id(feature))
            continue
        feature.type = source.type
        for key in ('label', 'source_type', 'source_id', 'source_level',
                    'source_revision', 'source_container'):
            if key in source.qualifiers:
                feature.qualifiers[key] = _values(source.qualifiers[key])
        # These colors were generated by the engine's filename fallback, not
        # supplied by the user. Replace them with the actual source style.
        for key in ('color', 'ApEinfo_fwdcolor', 'ApEinfo_revcolor'):
            feature.qualifiers.pop(key, None)
            if first(source.qualifiers, key):
                feature.qualifiers[key] = _values(source.qualifiers[key])
        apply_feature_color(feature)
    record.features = [f for f in record.features if id(f) not in removed]
    return record


def normalized_record(record):
    result = deepcopy(record)
    result.seq = Seq(str(result.seq).upper())
    length = len(result)
    circular = result.annotations.get('topology', '').lower() == 'circular'
    kept, seen_features = [], {}
    for feature in result.features:
        if feature.location is None or not length:
            continue
        parts = []
        try:
            for part in feature.location.parts:
                start, end = int(part.start), int(part.end)
                size = end - start
                if size <= 0 or size > length:
                    raise ValueError('invalid segment size')
                if circular:
                    start %= length
                    end = start + size
                elif start < 0 or end > length:
                    raise ValueError('linear feature outside sequence')
                if end <= length:
                    segments = [SimpleLocation(start, end, strand=part.strand)]
                else:
                    segments = [SimpleLocation(start, length, strand=part.strand),
                                SimpleLocation(0, end - length, strand=part.strand)]
                    if part.strand == -1:
                        segments.reverse()
                parts.extend(segments)
        except (TypeError, ValueError, OverflowError):
            continue
        if not parts or sum(len(p) for p in parts) > length:
            continue
        feature.location = parts[0] if len(parts) == 1 else CompoundLocation(
            parts, operator=getattr(feature.location, 'operator', 'join'))
        feature.qualifiers = {str(k): _values(v) for k, v in feature.qualifiers.items()}
        # Keep opposite strands and source containers distinct from internal features.
        key = (feature.type.casefold(),
               tuple((int(p.start), int(p.end), p.strand) for p in parts),
               first(feature.qualifiers, 'source_container'),
               first(feature.qualifiers, 'source_type'), first(feature.qualifiers, 'source_id'))
        if key in seen_features:
            existing = seen_features[key]
            aliases = list(dict.fromkeys(
                _values(existing.qualifiers.get('aliases')) +
                _values(feature.qualifiers.get('label')) +
                _values(feature.qualifiers.get('aliases'))))
            aliases = [x for x in aliases if x != first(existing.qualifiers, 'label')]
            if aliases:
                existing.qualifiers['aliases'] = aliases
            continue
        seen_features[key] = feature
        # Groups belong to occurrences, not just source features: a source may
        # be inserted multiple times. Generate IDs only after normalization.
        feature.qualifiers.setdefault('feature_group', [str(uuid.uuid4())])
        kept.append(feature)
    # Repeated inherited group IDs must not collapse distinct occurrences.
    groups = set()
    for feature in kept:
        apply_feature_color(feature)
        group = first(feature.qualifiers, 'feature_group')
        if group in groups:
            group = str(uuid.uuid4())
            feature.qualifiers['feature_group'] = [group]
        groups.add(group)
    result.features = kept
    result.annotations.setdefault('molecule_type', 'DNA')
    return result


def feature_rows(record):
    rows = []
    for feature in record.features:
        group = first(feature.qualifiers, 'feature_group') or str(uuid.uuid4())
        color = first(feature.qualifiers, 'color', first(feature.qualifiers, 'ApEinfo_fwdcolor'))
        for order, part in enumerate(feature.location.parts):
            rows.append({
                'feature_start': int(part.start) + 1, 'feature_end': int(part.end),
                'strand': part.strand, 'feature_group': group, 'segment_order': order,
                'location_operator': getattr(feature.location, 'operator', ''),
                'coordinate_system': 'one_based_closed',
                'feature_type': feature.type[:50],
                'feature_label': first(feature.qualifiers, 'label', first(feature.qualifiers, 'gene'))[:50],
                'feature_color': color[:50],
                'feature_apeinfo': first(feature.qualifiers, 'ApEinfo_fwdcolor', color)[:50],
                'feature_metadata': deepcopy(feature.qualifiers),
            })
    return rows


def record_from_rows(sequence, rows, name='Exported', topology='circular'):
    record = SeqRecord(Seq(''.join(str(sequence).split())), id=name, name=name, description='.')
    record.annotations.update(molecule_type='DNA', topology=topology)
    groups = OrderedDict()
    for index, row in enumerate(rows):
        groups.setdefault(row.get('feature_group') or 'legacy-%s' % index, []).append(row)
    for group, members in groups.items():
        members.sort(key=lambda x: x.get('segment_order') or 0)
        head = members[0]
        parts = []
        try:
            for row in members:
                start, end = int(row['feature_start']), int(row['feature_end'])
                if start < 1 or end < 1:
                    raise ValueError('Closed-interval positions must be positive')
                # Legacy rows are not blindly migrated. Known closed rows and
                # old upload rows share this convention; unknown assembly rows
                # require restoration from an original map.
                strand = row.get('strand')
                if strand not in (-1, 0, 1, None):
                    raise ValueError('invalid strand')
                if start > end and topology == 'circular':
                    span = [SimpleLocation(start - 1, len(record), strand),
                            SimpleLocation(0, end, strand)]
                    if strand == -1:
                        span.reverse()
                    parts.extend(span)
                else:
                    parts.append(SimpleLocation(start - 1, end, strand))
            location = parts[0] if len(parts) == 1 else CompoundLocation(
                parts, operator=head.get('location_operator') or 'join')
        except (KeyError, TypeError, ValueError, OverflowError):
            continue
        qualifiers = deepcopy(head.get('feature_metadata') or {})
        for key, field in [('label', 'feature_label'), ('color', 'feature_color'),
                           ('ApEinfo_fwdcolor', 'feature_apeinfo')]:
            if field in head:
                supplied = str(head.get(field) or '')
                if first(qualifiers, key)[:50] != supplied:
                    qualifiers[key] = [supplied]
        qualifiers.pop('segment_strands', None)
        qualifiers['feature_group'] = [group]
        record.features.append(SeqFeature(location, type=head.get('feature_type') or 'misc_feature',
                                          qualifiers=qualifiers))
    return record


def record_data(record):
    return {'id': record.id, 'name': record.name, 'description': record.description,
            'sequence': str(record.seq), 'topology': record.annotations.get('topology', 'circular'),
            'features': [{'type': f.type, 'operator': getattr(f.location, 'operator', ''),
                          'parts': [[int(p.start), int(p.end), p.strand] for p in f.location.parts],
                          'qualifiers': {k: _values(v) for k, v in f.qualifiers.items()}}
                         for f in record.features]}


def record_from_data(data):
    record = SeqRecord(Seq(data['sequence']), id=data['id'], name=data['name'],
                       description=data.get('description', '.'))
    record.annotations.update(molecule_type='DNA', topology=data['topology'])
    for feature in data['features']:
        parts = [SimpleLocation(s, e, strand) for s, e, strand in feature['parts']]
        location = parts[0] if len(parts) == 1 else CompoundLocation(parts, feature['operator'] or 'join')
        record.features.append(SeqFeature(location, type=feature['type'],
                                         qualifiers=deepcopy(feature['qualifiers'])))
    return record


def digest(value):
    return hashlib.sha256(json.dumps(value, ensure_ascii=False, sort_keys=True,
                                    separators=(',', ':')).encode('utf-8')).hexdigest()


def semantic_data(record):
    data = record_data(record)
    # GenBank readers uppercase bases; letter case is not a sequence change.
    data['sequence'] = data['sequence'].upper()
    # GenBank represents unstranded locations as forward unless explicitly
    # restored by our qualifier below. IDs/descriptions are presentation only.
    return {k: data[k] for k in ('sequence', 'topology', 'features')}


def genbank_text(record):
    exported = deepcopy(record)
    exported.annotations.setdefault('molecule_type', 'DNA')
    for feature in exported.features:
        feature.qualifiers['segment_strands'] = [json.dumps([p.strand for p in feature.location.parts])]
    buffer = io.StringIO()
    SeqIO.write(exported, buffer, 'genbank')
    text = buffer.getvalue()
    parsed = read_genbank(io.StringIO(text))
    if semantic_data(parsed) != semantic_data(record):
        raise ValueError('GenBank serialization changed sequence or annotations')
    return text


def read_genbank(source):
    record = SeqIO.read(source, 'genbank')
    for feature in record.features:
        for key in ('source_revision', 'feature_group', 'parent_feature_group', 'source_id'):
            if key in feature.qualifiers:
                feature.qualifiers[key] = [''.join(v.split()) for v in feature.qualifiers[key]]
        value = feature.qualifiers.pop('segment_strands', None)
        if value:
            strands = json.loads(''.join(value))
            if len(strands) != len(feature.location.parts):
                raise ValueError('Invalid segment strand metadata')
            for part, strand in zip(feature.location.parts, strands):
                part.strand = strand
    return record


def atomic_write(path, content):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix='.map-', dir=path.parent)
    try:
        with os.fdopen(fd, 'w', encoding='utf-8', newline='\n') as stream:
            stream.write(content)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def write_record(path, record):
    atomic_write(path, genbank_text(record))
